# Generated by Django 3.1.5 on 2021-01-31 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_play',
            field=models.CharField(default='a', max_length=500),
        ),
    ]
