# Generated by Django 3.1.5 on 2021-02-01 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_song_play'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_play',
            field=models.FileField(upload_to='songs'),
        ),
    ]
